routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

//Route::auth();

// Admin middleware
Route::group(['middleware'=>'admin', 'as' => 'admin.'], function(){

	Route::get('/admin', function(){
		return view('admin.index');
	});

	//User
	Route::resource('/admin/users', 'AdminUsersController');
	//Route::get('admin/media/upload',['as'=>'admin.media.upload', 'uses'=>'AdminMediasController@store']);

	//Product
	Route::get('/admin/products/autocomplete', 'ProductController@autocomplete')->name('products.autocomplete');
	Route::get('/admin/products/search', 'ProductController@search')->name('products.search');
	Route::get('/admin/products/export', 'ProductController@export')->name('products.export');
	Route::get('/admin/products', 'ProductController@index')->name('products');
	Route::post('/admin/products/store', 'ProductController@store')->name('products.store');
	Route::get('/admin/products/edit/{id}', 'ProductController@edit')->name('products.edit');
	Route::patch('/admin/products/update/{id}', 'ProductController@update')->name('products.update');
	Route::delete('/admin/products/destroy/{id}', 'ProductController@destroy')->name('products.destroy');
	Route::get('/admin/products/restore/{id}', 'ProductController@restore')->name('products.restore');
	Route::get('/admin/products/getAjaxValue/', 'ProductController@getAjaxValue')->name('products.getAjaxValue');

	// category 
	Route::resource('/admin/categories', 'CategoryController');

	// attribute 
	Route::resource('/admin/attributes', 'AttributeController');
	Route::get('/admin/attributes/restore/{id}', 'AttributeController@restore')->name('attributes.restore');

	// attribute value
	Route::get('/admin/attribute-values/{id}', 'AttributeValueController@index')->name('attribute-values');
	Route::post('/admin/attribute-values/store', 'AttributeValueController@store')->name('attribute-values.store');
	Route::get('/admin/attribute-values/value/{id}/attribute/{attr_id}', ['as' => 'attribute-values.edit', 'uses' => 'AttributeValueController@edit']);
	Route::patch('/admin/attribute-values/update/{id}', 'AttributeValueController@update')->name('attribute-values.update');
	Route::delete('/admin/attribute-values/destroy/{id}/attribute/{attr_id}', 'AttributeValueController@destroy')->name('attribute-values.destroy');
	Route::get('/admin/attribute-values/restore/{id}', 'AttributeValueController@restore')->name('attribute-values.restore');

	//supplier
	Route::resource('/admin/suppliers', 'SupplierController');

	//customers
	Route::resource('/admin/customers', 'CustomerController');
	Route::get('/admin/customers/restore/{id}', 'CustomerController@restore')->name('customers.restore');

	//Order
	Route::get('/admin/orders/search', 'OrderController@search')->name('orders.search');
	Route::get('/admin/orders/getCustomerName', 'OrderController@getCustomerName')->name('orders.getCustomerName');
	Route::get('/admin/orders/getOrderNo', 'OrderController@getOrderNo')->name('orders.getOrderNo');
	Route::get('/admin/orders', 'OrderController@index')->name('orders');
	Route::post('/admin/orders/store', 'OrderController@store')->name('orders.store');
	Route::get('/admin/orders/edit/{id}', 'OrderController@edit')->name('orders.edit');
	Route::patch('/admin/orders/update/{id}', 'OrderController@update')->name('orders.update');
	Route::delete('/admin/orders/destroy/{id}', 'OrderController@destroy')->name('orders.destroy');
	Route::get('/admin/orders/restore/{id}', 'OrderController@restore')->name('orders.restore');
	Route::get('/admin/orders/autocomplete_name', 'OrderController@autocomplete_name')->name('orders.autocomplete_name');
	Route::get('/admin/orders/autocomplete_multiple', 'OrderController@autocomplete_multiple')->name('orders.autocomplete_multiple');
});


// Business Owner middleware
// Route::group(['middleware'=>'bowner', 'as' => 'bowner.'], function(){

// 	// Homepage
// 	Route::get('/bowner', function(){
// 		return view('bowner.index');
// 	});

// 	// Human Resource route
// 	Route::resource('/bowner/humans', 'BownerHumansController');

// 	// Salary route
// 	Route::post('/bowner/salaries', 'BownerSalariesController@index');
// 	Route::post('/bowner/salaries/store', [
// 		'uses' => 'BownerSalariesController@store',
// 		'as' => 'salaries.store' ]);
// 	Route::resource('/bowner/salaries', 'BownerSalariesController', ['except'=>['store']]);

// 	// Leave route
// 	Route::resource('/bowner/leaves', 'LeavesController');

// 	// Chart route
// 	Route::get('bowner/chart', [
// 		'uses' => 'ChartController@index',
// 		'as' =>'chart.index'
// 	]);

// 	// Customer route
// 	Route::resource('bowner/customer', 'CustomerController', ['except'=>['store']]);

// 	// Order route
// 	// Route::get('order_delete/{order_id}',[
// 	// 	'uses' => 'OrderController@destroy',
// 	// 	'as' => 'orders.destroy',
// 	// ]);
// 	// Route::get('order_complete/{order_id}',[
// 	// 	'uses' => 'OrderController@complete',
// 	// 	'as' =>'orders.complete',
// 	// ]);
// 	// Route::get('order_submit/{order_id}', [
// 	// 	'uses' => 'OrderController@submit',
// 	// 	'as' => 'orders.submit',
// 	// ]);
// 	// Route::get('order_deliver/{order_id}', [
// 	// 	'uses' => 'OrderController@deliver',
// 	// 	'as' => 'orders.deliver',
// 	// ]);

// 	/*
// 	Route::get('bowner/inventories/material/purchase', [
// 		'uses' => 'MaterialPurchaseController@index',
// 		'as' => 'purchase.index'
// 	]);
// 	Route::get('bowner/inventories/material/purchase/create', [
// 		'uses' => 'MaterialPurchaseController@create',
// 		'as' => 'purchase.create'
// 	]);
// 	Route::post('bowner/inventories/material/purchase/store', [
// 		'uses' => 'MaterialPurchaseController@store',
// 		'as' => 'purchase.store'
// 	]);
// 	*/
// });

// // Order route
// /*
// Route::group(['middleware'=>'auth'], function(){
// 	Route::resource('/orders', 'OrderController', ['except'=>['destroy']]);
// 	Route::get('/delete_order/{order_id}',[
// 		'uses' => 'OrderController@destroy',
// 		'as' => 'orders.destroy',
// 	]);
// 	Route::get('/complete_order/{order_id}',[
// 		'uses' => 'OrderController@complete',
// 		'as' =>'orders.complete',
// 	]);
// */
// // BusinessOwner_Manager middleware
// Route::group(['middleware' => 'bowner_manager', 'as' => 'bowner.'], function() {

// 	Route::get('manager', function(){
// 		return view('bowner.index');
// 	});

// 	// Production route
// 	// Route::resource('bowner/production', 'ProductionController');
// 	// Route::get('bowner/complete_production/{o_qty}/{p_id}/{p_qty}',[
// 	// 	'uses' => 'ProductionController@complete',
// 	// 	'as' =>'production.complete',
// 	// ]);

// 	// Inventories route
// 	Route::resource('bowner/inventories', 'InventoryController');

// 	// Route::get('bowner/inventories/product/edit/{product_id}', [
// 	// 	'uses' => 'InventoryController@editProduct',
// 	// 	'as' => 'inventories.product.edit'
// 	// ]);
// 	// Route::get('bowner/inventories/material/edit/{material_id}', [
// 	// 	'uses' => 'InventoryController@editMaterial',
// 	// 	'as' => 'inventories.material.edit'
// 	// ]);
// 	// Route::patch('bowner/inventories/product/update/{product_id}', [
// 	// 	'uses' => 'InventoryController@updateProduct',
// 	// 	'as' => 'inventories.product.update'
// 	// ]);
// 	// Route::patch('bowner/inventories/material/update/{material_id}', [
// 	// 	'uses' => 'InventoryController@updateMaterial',
// 	// 	'as' => 'inventories.material.update'
// 	// ]);

// 	// Purchasing route
// 	Route::resource('bowner/inventories/material/purchase', 'MaterialPurchaseController', ['except'=>'destroy']);
// 	Route::get('bowner/inventories/material/purchase/delete/{purchase_id}', [
// 		'uses' => 'MaterialPurchaseController@destroy',
// 		'as' => 'purchase.destroy'
// 	]);
// 	Route::get('bowner/inventories/material/purchase/complete/{purchase_id}', [
// 		'uses' => 'MaterialPurchaseController@complete',
// 		'as' => 'purchase.complete'
// 	]);

// 	// Supplier route
// 	Route::resource('bowner/supplier', 'SupplierController');

// });

// // Employee_BusinessOwner middleware
// Route::group(['middleware' => 'bowner_employee'], function() {

// 	// Order route
// 	// Route::resource('orders', 'OrderController', ['except'=>['destroy']]);

// 	// Customer creation route
// 	Route::get('customer/create', 'CustomerController@create');
// 	Route::post('customer', 'CustomerController@store')->name('customer');
// });

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    // protected $guarded = [];
    use SoftDeletes;

    public function products(){
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use DB;
use Auth;
use Validator;
use App\User;
use App\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suppliers = Supplier::paginate(10);

        return view('admin.suppliers.index', compact('suppliers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        // return view('admin.supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'name' => 'required|unique:suppliers,name',
            'address1' => 'required',
            // 'phone' => 'required|regex:/(09)[0-9]{9}/',
            'phone' => 'required',
            'contact' => 'required',
            'email' => 'required|unique:suppliers,mail',
        ]);

        if($validator->fails()) {
            return redirect('admin/suppliers')
                        ->withErrors($validator)
                        ->withInput();
        }

        DB::beginTransaction();

        try {
            $supplier = new Supplier();
            $supplier->user_id = Auth::user()->id;
            $supplier->name = $data['name'];
            $supplier->address1 = $data['address1'];
            $supplier->address2 = ($data['address2'] != '') ? $data['address2'] : null;
            $supplier->phone = $data['phone'];
            $supplier->contact_person = $data['contact'];
            $supplier->mail = $data['email'];
            $supplier->description = ($data['description'] != '') ? $data['description'] : null;
            $supplier->save();

            DB::commit();

            Session::flash('created_message', 'The supplier has been created');
            return redirect()->back();
        } catch (\Exception $e) {

            DB::rollBack();

            Session::flash('error_message', 'Failed !! The supplier has not been created');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = Supplier::find($id);
// dd($supplier);
        return view('admin.suppliers.edit', compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'name' => 'required|unique:suppliers,name,'.$id,
            'address1' => 'required',
            // 'phone' => 'required|regex:/(09)[0-9]{9}/',
            'phone' => 'required|unique:suppliers,phone,'.$id,
            'contact' => 'required',
            'email' => 'required|unique:suppliers,mail,'.$id,
        ]);

        if($validator->fails()) {
            return redirect('admin/suppliers')
                        ->withErrors($validator)
                        ->withInput();
        }

        $supplier = Supplier::find($id);
        $supplier->user_id = Auth::user()->id;
        $supplier->name = $data['name'];
        $supplier->address1 = $data['address1'];
        $supplier->address2 = ($data['address2'] != '' ) ? $data['address2'] : null;
        $supplier->phone = $data['phone'];
        $supplier->contact_person = $data['contact'];
        $supplier->mail = $data['email'];
        $supplier->description = ($data['description'] != '' ) ? $data['description'] : null;
        $supplier->update();

        Session::flash('updated_message', 'The supplier has been updated');
        return redirect('admin/suppliers');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::find($id);
        $supplier->delete();

        Session::flash('deleted_message', 'The supplier has been deleted');
        return redirect('admin/suppliers');
    }
}

resources/views/admin/suppliers/edit.blade.php
@extends('layouts.admin')

@section('content')

	<h1>Supplier</h1>

    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
	@endif

    <!-- Start .nav nav-tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presenstation"><a><strong>Edit Supplier</strong></a></li>
	</ul>
	<!-- End .nav nav-tabs -->
    <div class="container " style="padding: 10px;">
        <div class="col-md-12">
            <div class="panel panel-default">
                    <div class="panel-heading">
                        Edit Supplier
                    </div>

                    <div class="panel-body">
                        <!-- Edit Supplier -->
                        <form action="{{ route('admin.suppliers.update', $supplier->id) }}" method="POST" class="form-horizontal">
                        @csrf
                        @method('PATCH')

                            <div class="row clearfix">
                                <div class="form-group col-md-12">
                                    <label for="name" class="control-label">Name</label>
                                    <input type="text" name="name" id="name" class="form-control" value="{{ $supplier->name }}">
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="address1" class="control-label">Address 1</label>
                                    <input type="text" name="address1" id="address1" class="form-control" value="{{ $supplier->address1 }}">
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="address2" class="control-label">Address 2</label>
                                    <input type="text" name="address2" id="address2" class="form-control" value="{{ $supplier->address2 }}">
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="phone" class="control-label">Phone</label>
                                    <input type="text" name="phone" id="phone" class="form-control" value="{{ $supplier->phone }}">
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="contact" class="control-label">Contact Person</label>
                                    <input type="text" name="contact" id="contact" class="form-control" value="{{ $supplier->contact_person }}">
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="email" class="control-label">Mail</label>
                                    <input type="email" name="email" id="email" class="form-control" value="{{ $supplier->mail }}">
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="description" class="control-label">Description</label>
                                    <textarea name="description" id="description" cols="30" rows="10" class="form-control">{{ $supplier->description }}</textarea>
                                </div>
                            </div>

                            <div class="row clearfix" style="float:right;">
                                <button type="submit" class="btn btn-success">
                                    Update
                                </button>
                            </div>
                        </form>
                    </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/suppliers/index.blade.php
@extends('layouts.admin')

@section('content')

{{ Breadcrumbs::render('suppliers', $suppliers) }}

	<h1>Supplier</h1>

    @include('includes.message')

    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
	@endif

    <!-- Start .nav nav-tabs -->
	<ul class="nav nav-tabs" role="tablist">
		<li role="presenstation" class="active"><a href="#view" aria-controls="view" role="tab" data-toggle="tab"><strong>View Suppliers</strong></a></li>
		<li role="presenstation"><a href="#create" aria-controls="create" role="tab" data-toggle="tab"><strong>Create Supplier</strong></a></li>
	</ul>
	<!-- End .nav nav-tabs -->

    <div class="tab-content">
		<!-- Show Suppliers -->
		<div role="tabpanel1" class="tab-pane fade in active" id="view">
            <div class="container">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Supplier Lists
                        </div>

                        <div class="panel-body">
                            <!-- Supplier List -->
                            <table class="table table-striped ">
                                <thead">
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Address1</th>
                                    <th>Phone</th>
                                    <th>Contact Person</th>
                                    <th>Mail</th>
                                    <th>Join Date</th>
                                    <th>Created By</th>
                                    <th>Actions</th>
                                </thead>

                                <tbody>
                                    @foreach($suppliers as $supplier)
                                    <tr>
                                        <td>{{ $supplier->id }}</td>
                                        <td>{{ $supplier->name }}</td>
                                        <td>{{ $supplier->address1 }}</td>
                                        <td>{{ $supplier->phone }}</td>
                                        <td>{{ $supplier->contact_person }}</td>
                                        <td>{{ $supplier->mail }}</td>
                                        <td>{{ $supplier->created_at->diffForHumans() }}</td>
                                        <td>{{ Auth::user()->name }}</td>
                                        <td>
                                            <a href="{{ route('admin.suppliers.edit', $supplier->id) }}" class="btn btn-primary btn-xs"><i class="material-icons">edit</i></a>
                                            <form action="{{ route('admin.suppliers.destroy', $supplier->id) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                                <button class="btn btn-danger btn-xs"><i class="material-icons">delete</i></button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $suppliers->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End .tab-pane -->
        <!-- End Show Product -->

        <!-- Create Supplier -->
        <div role="tabpanel2" class="tab-pane fade" id="create" style="padding: 20px;">
            <div class="container">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            New Supplier
                        </div>

                        <div class="panel-body">
                            <!-- New Supplier -->
                            <form action="{{ route('admin.suppliers.store') }}" method="POST" class="form-horizontal">
                            {{ csrf_field() }}

                                <div class="row clearfix">
                                    <div class="form-group col-md-12">
                                        <label for="name" class="control-label">Name</label>
                                        <input type="text" name="name" id="name" class="form-control">
                                    </div>

                                    <div class="form-group col-md-12">
                                        <label for="address1" class="control-label">Address 1</label>
                                        <input type="text" name="address1" id="address1" class="form-control">
                                    </div>

                                    <div class="form-group col-md-12">
                                        <label for="address2" class="control-label">Address 2</label>
                                        <input type="text" name="address2" id="address2" class="form-control">
                                    </div>

                                    <div class="form-group col-md-12">
                                        <label for="phone" class="control-label">Phone</label>
                                        <input type="text" name="phone" id="phone" class="form-control">
                                    </div>

                                    <div class="form-group col-md-12">
                                        <label for="contact" class="control-label">Contact Person</label>
                                        <input type="text" name="contact" id="contact" class="form-control">
                                    </div>

                                    <div class="form-group col-md-12">
                                        <label for="email" class="control-label">Mail</label>
                                        <input type="email" name="email" id="email" class="form-control">
                                    </div>

                                    <div class="form-group col-md-12">
                                        <label for="description" class="control-label">Description</label>
                                        <textarea name="description" id="description" cols="30" rows="10" class="form-control"></textarea>
                                    </div>
                                </div>

                                <div class="row clearfix" style="float:right;">
                                    <button type="submit" class="btn btn-success">
                                        <i class="fa fa-plus"></i> Add
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End .tab-pane -->
        <!-- End Create Product -->
	</div>
	<!-- End .tab-content -->

@endsection