routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

//Route::auth();

// Admin middleware
Route::group(['middleware'=>'admin', 'as' => 'admin.'], function(){

	Route::get('/admin', function(){
		return view('admin.index');
	});

	//User
	Route::resource('/admin/users', 'AdminUsersController');
	//Route::get('admin/media/upload',['as'=>'admin.media.upload', 'uses'=>'AdminMediasController@store']);

	//Product
	Route::get('/admin/products/autocomplete', 'ProductController@autocomplete')->name('products.autocomplete');
	Route::get('/admin/products/search', 'ProductController@search')->name('products.search');
	Route::get('/admin/products/export', 'ProductController@export')->name('products.export');
	Route::get('/admin/products', 'ProductController@index')->name('products');
	Route::post('/admin/products/store', 'ProductController@store')->name('products.store');
	Route::get('/admin/products/edit/{id}', 'ProductController@edit')->name('products.edit');
	Route::patch('/admin/products/update/{id}', 'ProductController@update')->name('products.update');
	Route::delete('/admin/products/destroy/{id}', 'ProductController@destroy')->name('products.destroy');
	Route::get('/admin/products/restore/{id}', 'ProductController@restore')->name('products.restore');
	Route::get('/admin/products/getAjaxValue/', 'ProductController@getAjaxValue')->name('products.getAjaxValue');

	// category 
	Route::resource('/admin/categories', 'CategoryController');

	// attribute 
	Route::resource('/admin/attributes', 'AttributeController');
	Route::get('/admin/attributes/restore/{id}', 'AttributeController@restore')->name('attributes.restore');

	// attribute value
	Route::get('/admin/attribute-values/{id}', 'AttributeValueController@index')->name('attribute-values');
	Route::post('/admin/attribute-values/store', 'AttributeValueController@store')->name('attribute-values.store');
	Route::get('/admin/attribute-values/value/{id}/attribute/{attr_id}', ['as' => 'attribute-values.edit', 'uses' => 'AttributeValueController@edit']);
	Route::patch('/admin/attribute-values/update/{id}', 'AttributeValueController@update')->name('attribute-values.update');
	Route::delete('/admin/attribute-values/destroy/{id}/attribute/{attr_id}', 'AttributeValueController@destroy')->name('attribute-values.destroy');
	Route::get('/admin/attribute-values/restore/{id}', 'AttributeValueController@restore')->name('attribute-values.restore');

	//supplier
	Route::resource('/admin/suppliers', 'SupplierController');

	//customers
	Route::resource('/admin/customers', 'CustomerController');
	Route::get('/admin/customers/restore/{id}', 'CustomerController@restore')->name('customers.restore');

	//Order
	Route::get('/admin/orders/search', 'OrderController@search')->name('orders.search');
	Route::get('/admin/orders/getCustomerName', 'OrderController@getCustomerName')->name('orders.getCustomerName');
	Route::get('/admin/orders/getOrderNo', 'OrderController@getOrderNo')->name('orders.getOrderNo');
	Route::get('/admin/orders', 'OrderController@index')->name('orders');
	Route::post('/admin/orders/store', 'OrderController@store')->name('orders.store');
	Route::get('/admin/orders/edit/{id}', 'OrderController@edit')->name('orders.edit');
	Route::patch('/admin/orders/update/{id}', 'OrderController@update')->name('orders.update');
	Route::delete('/admin/orders/destroy/{id}', 'OrderController@destroy')->name('orders.destroy');
	Route::get('/admin/orders/restore/{id}', 'OrderController@restore')->name('orders.restore');
	Route::get('/admin/orders/autocomplete_name', 'OrderController@autocomplete_name')->name('orders.autocomplete_name');
	Route::get('/admin/orders/autocomplete_multiple', 'OrderController@autocomplete_multiple')->name('orders.autocomplete_multiple');
});


// Business Owner middleware
// Route::group(['middleware'=>'bowner', 'as' => 'bowner.'], function(){

// 	// Homepage
// 	Route::get('/bowner', function(){
// 		return view('bowner.index');
// 	});

// 	// Human Resource route
// 	Route::resource('/bowner/humans', 'BownerHumansController');

// 	// Salary route
// 	Route::post('/bowner/salaries', 'BownerSalariesController@index');
// 	Route::post('/bowner/salaries/store', [
// 		'uses' => 'BownerSalariesController@store',
// 		'as' => 'salaries.store' ]);
// 	Route::resource('/bowner/salaries', 'BownerSalariesController', ['except'=>['store']]);

// 	// Leave route
// 	Route::resource('/bowner/leaves', 'LeavesController');

// 	// Chart route
// 	Route::get('bowner/chart', [
// 		'uses' => 'ChartController@index',
// 		'as' =>'chart.index'
// 	]);

// 	// Customer route
// 	Route::resource('bowner/customer', 'CustomerController', ['except'=>['store']]);

// 	// Order route
// 	// Route::get('order_delete/{order_id}',[
// 	// 	'uses' => 'OrderController@destroy',
// 	// 	'as' => 'orders.destroy',
// 	// ]);
// 	// Route::get('order_complete/{order_id}',[
// 	// 	'uses' => 'OrderController@complete',
// 	// 	'as' =>'orders.complete',
// 	// ]);
// 	// Route::get('order_submit/{order_id}', [
// 	// 	'uses' => 'OrderController@submit',
// 	// 	'as' => 'orders.submit',
// 	// ]);
// 	// Route::get('order_deliver/{order_id}', [
// 	// 	'uses' => 'OrderController@deliver',
// 	// 	'as' => 'orders.deliver',
// 	// ]);

// 	/*
// 	Route::get('bowner/inventories/material/purchase', [
// 		'uses' => 'MaterialPurchaseController@index',
// 		'as' => 'purchase.index'
// 	]);
// 	Route::get('bowner/inventories/material/purchase/create', [
// 		'uses' => 'MaterialPurchaseController@create',
// 		'as' => 'purchase.create'
// 	]);
// 	Route::post('bowner/inventories/material/purchase/store', [
// 		'uses' => 'MaterialPurchaseController@store',
// 		'as' => 'purchase.store'
// 	]);
// 	*/
// });

// // Order route
// /*
// Route::group(['middleware'=>'auth'], function(){
// 	Route::resource('/orders', 'OrderController', ['except'=>['destroy']]);
// 	Route::get('/delete_order/{order_id}',[
// 		'uses' => 'OrderController@destroy',
// 		'as' => 'orders.destroy',
// 	]);
// 	Route::get('/complete_order/{order_id}',[
// 		'uses' => 'OrderController@complete',
// 		'as' =>'orders.complete',
// 	]);
// */
// // BusinessOwner_Manager middleware
// Route::group(['middleware' => 'bowner_manager', 'as' => 'bowner.'], function() {

// 	Route::get('manager', function(){
// 		return view('bowner.index');
// 	});

// 	// Production route
// 	// Route::resource('bowner/production', 'ProductionController');
// 	// Route::get('bowner/complete_production/{o_qty}/{p_id}/{p_qty}',[
// 	// 	'uses' => 'ProductionController@complete',
// 	// 	'as' =>'production.complete',
// 	// ]);

// 	// Inventories route
// 	Route::resource('bowner/inventories', 'InventoryController');

// 	// Route::get('bowner/inventories/product/edit/{product_id}', [
// 	// 	'uses' => 'InventoryController@editProduct',
// 	// 	'as' => 'inventories.product.edit'
// 	// ]);
// 	// Route::get('bowner/inventories/material/edit/{material_id}', [
// 	// 	'uses' => 'InventoryController@editMaterial',
// 	// 	'as' => 'inventories.material.edit'
// 	// ]);
// 	// Route::patch('bowner/inventories/product/update/{product_id}', [
// 	// 	'uses' => 'InventoryController@updateProduct',
// 	// 	'as' => 'inventories.product.update'
// 	// ]);
// 	// Route::patch('bowner/inventories/material/update/{material_id}', [
// 	// 	'uses' => 'InventoryController@updateMaterial',
// 	// 	'as' => 'inventories.material.update'
// 	// ]);

// 	// Purchasing route
// 	Route::resource('bowner/inventories/material/purchase', 'MaterialPurchaseController', ['except'=>'destroy']);
// 	Route::get('bowner/inventories/material/purchase/delete/{purchase_id}', [
// 		'uses' => 'MaterialPurchaseController@destroy',
// 		'as' => 'purchase.destroy'
// 	]);
// 	Route::get('bowner/inventories/material/purchase/complete/{purchase_id}', [
// 		'uses' => 'MaterialPurchaseController@complete',
// 		'as' => 'purchase.complete'
// 	]);

// 	// Supplier route
// 	Route::resource('bowner/supplier', 'SupplierController');

// });

// // Employee_BusinessOwner middleware
// Route::group(['middleware' => 'bowner_employee'], function() {

// 	// Order route
// 	// Route::resource('orders', 'OrderController', ['except'=>['destroy']]);

// 	// Customer creation route
// 	Route::get('customer/create', 'CustomerController@create');
// 	Route::post('customer', 'CustomerController@store')->name('customer');
// });

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    public function products(){
        return $this->belongsToMany('App\Product')->withTimestamps();
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use DB;
use Validator;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\APIBaseController as APIBaseController;

class CategoryController extends APIBaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(10);
        return view('admin.categories.index', compact('categories'));

        // return $this->sendResponse($categories->toArray(), "Categories retrieved successfully");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $data = $request->all();
        $validator = Validator::make($data, [
            'name' => 'required|unique:categories'
        ]);

        if ($validator->fails()) {
            return redirect('admin/categories')
                        ->withErrors($validator)
                        ->withInput();

            // return $this->sendError('Validation Error.', $validator->errors());
        }

        DB::beginTransaction();

        try{
            $category = new Category();
            $category->name = $data['name'];
            $category->save();
            DB::commit();

            Session::flash('created_message', 'The category has been created');
            return redirect()->back();
            // return $this->sendResponse($category->toArray(), 'Category is successfully created');
        }catch(\Exception $e){
            DB::rollback();
            Session::flash('error_message', 'Failed !! The category has not been created');
            return redirect()->back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // dd($id);
        $category = Category::find($id);
        $categories = Category::get();
        return view('admin.categories.edit', compact('category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'name' => 'required|unique:categories,name,'.$id
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                        ->withErrors($validator)
                        ->withInput();
            // return $this->sendError('Validation Error.', $validator->errors());
        }

        $category = Category::find($id);
        if (is_null($category)) {
            return $this->sendError('Category not found.');
        }
        $category->name = $data['name'];
        $category->update();

        Session::flash('updated_message', 'The category has been updated');
        return redirect('admin/categories');
        // return $this->sendResponse($category->toArray(), 'Category is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        Session::flash('deleted_message', 'The category has been deleted');
        return redirect('admin/categories');
        // return $this->sendResponse($id, 'Category deleted successfully.');
    }
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')

	<h1>Category</h1>

    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
	@endif

    <ul class="nav nav-tabs">
		<li role="presenstation" class="active"><a href="#"><strong>View / Edit</strong></a></li>
	</ul>

    <div class="container " style="padding: 10px;">
        
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Category Lists
                </div>

                <div class="panel-body">
                    <!-- Category List -->
                    <table class="table table-striped text-center">
                        <thead">
                            <th class="text-center">ID</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Actions</th>
                        </thead>

                        <tbody>
                            @foreach($categories as $categorylist)
                            <tr>
                                <td>{{ $categorylist->id }}</td>
                                <td>{{ $categorylist->name }}</td>
                                <td>
                                <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-primary btn-xs" disabled><i class="material-icons">edit</i></a>
                                <form action="{{ route('admin.categories.destroy', $category->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                    <button class="btn btn-danger btn-xs" disabled><i class="material-icons">delete</i></button>
                                </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Edit Category
                </div>

                <div class="panel-body">
                    <!-- Edit Category -->
                    <form action="{{ route('admin.categories.update', $category->id) }}" method="POST" class="form-horizontal">
                    @csrf
                    @method('PATCH')

                        <div class="row clearfix">
                            <div class="form-group col-md-12">
                                <label for="name" class="control-label">Category</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{ $category->name }}">
                            </div>
                        </div>

                        <div class="row clearfix" style="float:right;">
                            <button type="submit" class="btn btn-success">
                                Update
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')

{{ Breadcrumbs::render('categories', $categories) }}

	<h1>Category</h1>

    @include('includes.message')

    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
	@endif

    <ul class="nav nav-tabs">
		<li role="presenstation" class="active"><a href="#"><strong>View / Create</strong></a></li>
	</ul>

    <div class="container " style="padding: 10px;">
        
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Category Lists
                </div>

                <div class="panel-body">
                    <!-- Category List -->
                    <table class="table table-striped text-center">
                        <thead">
                            <th class="text-center">ID</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Actions</th>
                        </thead>

                        <tbody>
                            @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->id }}</td>
                                <td>{{ $category->name }}</td>
                                <td>
                                <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-primary btn-xs"><i class="material-icons">edit</i></a>
                                <form action="{{ route('admin.categories.destroy', $category->id) }}" method="post">
                                @csrf
                                @method('DELETE')
                                    <button class="btn btn-danger btn-xs"><i class="material-icons">delete</i></button>
                                </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $categories->links() }}
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    New Category
                </div>

                <div class="panel-body">
                    <!-- New Category -->
                    <form action="{{ route('admin.categories.store') }}" method="POST" class="form-horizontal">
                    {{ csrf_field() }}

                        <div class="row clearfix">
                            <div class="form-group col-md-12">
                                <label for="name" class="control-label">Category</label>
                                <input type="text" name="name" id="name" class="form-control">
                            </div>
                        </div>

                        <div class="row clearfix" style="float:right;">
                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-plus"></i> Add
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection